# -*- coding: utf-8 -*-
"""NN_Project-02_Preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qNsEg0pNVvw9X-yrI60FB_RaSUqFlr6
"""

from google.colab import drive
drive.mount('/content/drive')

"""#### Install necessary Python libraries for LIDC-IDRI data processing.

*   pylidc: For programmatic access to LIDC-IDRI data
*   SimpleITK: For medical image processing
*   nibabel: For reading and writing neuroimaging files (general medical imaging)
*   numpy: For numerical operations, especially with arrays
*   pandas: For data manipulation and analysis
*   matplotlib: For plotting and visualization
*   tqdm: For progress bars
*   sqlalchemy: Database toolkit for pylidc
"""

!pip install -q pylidc SimpleITK nibabel numpy pandas matplotlib tqdm sqlalchemy

"""#### Define base directories for the project, raw data, metadata, and processed outputs."""

import os
import re
import numpy as np
import pandas as pd

BASE_DIR = "/content/drive/MyDrive/lung_nodule_project"
RAW_DIR = os.path.join(BASE_DIR, "lidc_subset_raw", "lidc_idri")
META_DIR = os.path.join(BASE_DIR, "metadata")
PROC_DIR = os.path.join(BASE_DIR, "lidc_patches_small")
PATCH_DIR = os.path.join(PROC_DIR, "patches")
MASK_DIR = os.path.join(PROC_DIR, "masks")

# Create these directories if they don't already exist
for d in [META_DIR, PROC_DIR, PATCH_DIR, MASK_DIR]:
    os.makedirs(d, exist_ok=True)

print("RAW_DIR:", RAW_DIR)
print("META_DIR:", META_DIR)
print("PROC_DIR:", PROC_DIR)

print("RAW_DIR exists:", os.path.exists(RAW_DIR))
print("First 20 items in RAW_DIR:")
print(os.listdir(RAW_DIR)[:20])

"""#### Save the list of patient IDs to a CSV file.

"""

# Define a regex pattern to identify patient folders (e.g., 'LIDC-IDRI-XXXX')
patient_pattern = re.compile(r"^LIDC-IDRI-\d{4}$")

patient_ids = sorted([
    d for d in os.listdir(RAW_DIR)
    if os.path.isdir(os.path.join(RAW_DIR, d)) and patient_pattern.match(d)
])

print("Patients found:", len(patient_ids))
print("First 10:", patient_ids[:10])

if len(patient_ids) == 0:
    raise RuntimeError("No patient folders found in RAW_DIR. Check the path again.")

selected_csv = os.path.join(META_DIR, "selected_patients_50.csv")
pd.Series(patient_ids).to_csv(selected_csv, index=False, header=False)

print("Saved:", selected_csv)

"""#### Configure pylidc
pylidc looks for ~/.pylidcrc on Linux/Colab, and the path should be the folder whose direct children are the patient folders.
"""

config_text = f"""[dicom]
path = {RAW_DIR}
warn = True
"""
with open(os.path.expanduser("~/.pylidcrc"), "w") as f:
    f.write(config_text)

# Confirm creation and print the contents of the config file
print("Created ~/.pylidcrc")
with open(os.path.expanduser("~/.pylidcrc"), "r") as f:
    print(f.read())

"""#### Summary of patients with and without nodules/errors"""

import configparser

# Fix for pylidc and numpy.int deprecation
if not hasattr(np, 'int'):
    np.int = int

# Compatibility fixes for older configparser versions if running in specific environments
if not hasattr(configparser, "SafeConfigParser"):
    configparser.SafeConfigParser = configparser.ConfigParser
if not hasattr(configparser.ConfigParser, "readfp"):
    configparser.ConfigParser.readfp = configparser.ConfigParser.read_file

import pylidc as pl
import pandas as pd

selected_csv = "/content/drive/MyDrive/lung_nodule_project/metadata/selected_patients_50.csv"
selected_patients = pd.read_csv(selected_csv, header=None).iloc[:, 0].astype(str).tolist()

good_patients = []
bad_patients = []

for pid in selected_patients:
    try:
        scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == pid).first()
        if scan is None:
            bad_patients.append((pid, "scan not found"))
            continue

        # Get clustered annotations (nodules) for the scan
        nodules = scan.cluster_annotations()

        if len(nodules) > 0:
            good_patients.append((pid, len(nodules)))
        else:
            bad_patients.append((pid, "no nodules"))
    except Exception as e:
        bad_patients.append((pid, str(e)))

print("Patients with nodules:", len(good_patients))
print("First 10 good patients:", good_patients[:10])

print("Patients without usable nodules/errors:", len(bad_patients))
print("First 10 bad patients:", bad_patients[:10])

"""#### Testing one patient"""

test_pid = good_patients[0][0]
print("Using test patient:", test_pid)

scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == test_pid).first()
# Convert the DICOM scan into a 3D NumPy volume (voxel data)
vol = scan.to_volume()
# Retrieve the clustered nodule annotations for this scan
nodules = scan.cluster_annotations()

print("Volume shape:", vol.shape)
print("Number of clustered nodules:", len(nodules))

"""#### Quick visual check with consensus mask
The consensus(...) utility returns a consensus mask, a shared bounding box, and individual masks for the clustered annotations.
"""

from pylidc.utils import consensus
import matplotlib.pyplot as plt

anns = nodules[0]

# Generate a consensus mask for the selected nodule annotations.
# clevel=0.5 means a voxel is part of the consensus mask if at least 50% of annotations agree.
# pad: Adds padding around the nodule bounding box for visualization.
cmask, cbbox, masks = consensus(
    anns,
    clevel=0.5,
    pad=[(20, 20), (20, 20), (0, 0)]
)

# Calculate the middle slice index (k) for the z-axis (depth) of the consensus mask
k = cmask.shape[2] // 2

plt.figure(figsize=(5, 5))
# Display the original CT scan slice corresponding to the nodule's bounding box
plt.imshow(vol[cbbox][:, :, k], cmap="gray")
# Overlay the consensus mask on top of the CT slice with transparency
plt.imshow(cmask[:, :, k], alpha=0.3, cmap="Reds")
plt.title(f"{test_pid} - consensus mask")
plt.axis("off")
plt.show()

"""#### Helper Functions"""

def normalize_hu(volume, hu_min=-1000, hu_max=400):
    volume = np.clip(volume, hu_min, hu_max)
    volume = (volume - hu_min) / (hu_max - hu_min)
    return volume.astype(np.float32)

def crop_patch(img2d, mask2d, center_x, center_y, patch_size=128):
    half = patch_size // 2

    x1 = max(0, center_x - half)
    x2 = min(img2d.shape[0], center_x + half)
    y1 = max(0, center_y - half)
    y2 = min(img2d.shape[1], center_y + half)

    crop_img = img2d[x1:x2, y1:y2]
    crop_msk = mask2d[x1:x2, y1:y2]

    out_img = np.zeros((patch_size, patch_size), dtype=np.float32)
    out_msk = np.zeros((patch_size, patch_size), dtype=np.uint8)

    out_img[:crop_img.shape[0], :crop_img.shape[1]] = crop_img
    out_msk[:crop_msk.shape[0], :crop_msk.shape[1]] = crop_msk

    return out_img, out_msk

"""#### The main preprocessing loop that iterates through all selected_patients."""

from tqdm import tqdm

meta_rows = []
failed_rows = []

for pid in tqdm(selected_patients):
    try:
        scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == pid).first()

        if scan is None:
            failed_rows.append([pid, "scan not found"])
            continue

        vol = normalize_hu(scan.to_volume())
        nodules = scan.cluster_annotations()

        if len(nodules) == 0:
            failed_rows.append([pid, "no clustered nodules"])
            continue

        for nodule_idx, ann_cluster in enumerate(nodules):
            try:
                cmask, cbbox, masks = consensus(
                    ann_cluster,
                    clevel=0.5,
                    pad=[(20, 20), (20, 20), (0, 0)]
                )

                z_slices = np.where(cmask.sum(axis=(0, 1)) > 0)[0]
                if len(z_slices) == 0:
                    failed_rows.append([pid, f"empty mask nodule {nodule_idx}"])
                    continue

                k = z_slices[len(z_slices) // 2]

                local_img = vol[cbbox][:, :, k]
                local_msk = cmask[:, :, k].astype(np.uint8)

                xs, ys = np.where(local_msk > 0)
                if len(xs) == 0:
                    failed_rows.append([pid, f"no positive pixels nodule {nodule_idx}"])
                    continue

                cx = int(np.mean(xs))
                cy = int(np.mean(ys))

                patch, mpatch = crop_patch(local_img, local_msk, cx, cy, patch_size=128)

                fname = f"{pid}_n{nodule_idx}_z{k}.npy"
                np.save(os.path.join(PATCH_DIR, fname), patch)
                np.save(os.path.join(MASK_DIR, fname), mpatch)

                meta_rows.append({
                    "patient_id": pid,
                    "nodule_id": nodule_idx,
                    "slice_idx": int(k),
                    "patch_file": fname,
                    "mask_file": fname
                })

            except Exception as e:
                failed_rows.append([pid, f"nodule {nodule_idx}: {str(e)}"])

    except Exception as e:
        failed_rows.append([pid, str(e)])

meta_df = pd.DataFrame(meta_rows)
failed_df = pd.DataFrame(failed_rows, columns=["patient_id", "error"])

meta_df.to_csv(os.path.join(PROC_DIR, "patch_meta.csv"), index=False)
failed_df.to_csv(os.path.join(PROC_DIR, "failed_patients.csv"), index=False)

print("Patches created:", len(meta_df))
print("Failed rows:", len(failed_df))
print(meta_df.head())

"""#### Loads an example patch and its mask from the processed data"""

import matplotlib.pyplot as plt

meta_df = pd.read_csv(os.path.join(PROC_DIR, "patch_meta.csv"))

if len(meta_df) == 0:
    raise RuntimeError("No patches were created. Check failed_patients.csv.")

sample = meta_df.iloc[0]

img = np.load(os.path.join(PATCH_DIR, sample["patch_file"]))
msk = np.load(os.path.join(MASK_DIR, sample["mask_file"]))

plt.figure(figsize=(10, 4))

plt.subplot(1, 3, 1)
plt.imshow(img, cmap="gray")
plt.title("Patch")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(msk, cmap="gray")
plt.title("Mask")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(img, cmap="gray")
plt.contour(msk, colors="r")
plt.title("Overlay")
plt.axis("off")

plt.tight_layout()
plt.show()

!cd /content/drive/MyDrive/lung_nodule_project && zip -r lidc_patches_small.zip lidc_patches_small